graph TD
    openldap["openldap"] --> busybox["busybox"]
    busybox["busybox"] --> so_libc_musl_x86_so_1["so:libc.musl-x86.so.1"]
    openldap["openldap"] --> so_libc_musl_x86_so_1["so:libc.musl-x86.so.1"]
    openldap["openldap"] --> so_liblber_2_4_so_2["so:liblber-2.4.so.2"]
    openldap["openldap"] --> so_libldap_r_2_4_so_2["so:libldap_r-2.4.so.2"]
    openldap["openldap"] --> so_libltdl_so_7["so:libltdl.so.7"]
    openldap["openldap"] --> so_libsasl2_so_3["so:libsasl2.so.3"]
    openldap["openldap"] --> so_libuuid_so_1["so:libuuid.so.1"]
