graph TD
    package-1000 --> package-817
    package-817 --> package-770
    package-770 --> package-724
    package-724 --> package-266
    package-266 --> package-161
    package-266 --> package-206
    package-206 --> package-164
    package-164 --> package-22
    package-22 --> package-19
    package-19 --> package-4
    package-19 --> package-13
    package-13 --> package-2
    package-2 --> package-1
    package-22 --> package-12
    package-12 --> package-7
    package-7 --> package-5
    package-5 --> package-2
    package-5 --> package-3
    package-5 --> package-1
    package-5 --> package-4
    package-7 --> package-4
    package-7 --> package-2
    package-12 --> package-9
    package-9 --> package-4
    package-12 --> package-8
    package-8 --> package-2
    package-12 --> package-1
    package-12 --> package-4
    package-22 --> package-17
    package-17 --> package-12
    package-17 --> package-13
    package-22 --> package-5
    package-164 --> package-134
    package-134 --> package-2
    package-134 --> package-1
    package-134 --> package-105
    package-105 --> package-68
    package-68 --> package-16
    package-16 --> package-3
    package-16 --> package-1
    package-16 --> package-8
    package-16 --> package-12
    package-105 --> package-2
    package-105 --> package-20
    package-105 --> package-78
    package-78 --> package-53
    package-53 --> package-38
    package-53 --> package-27
    package-53 --> package-44
    package-53 --> package-22
    package-53 --> package-20
    package-78 --> package-45
    package-45 --> package-20
    package-78 --> package-63
    package-63 --> package-58
    package-63 --> package-50
    package-63 --> package-54
    package-63 --> package-13
    package-78 --> package-58
    package-58 --> package-22
    package-58 --> package-50
    package-78 --> package-72
    package-72 --> package-31
    package-72 --> package-59
    package-72 --> package-69
    package-134 --> package-75
    package-75 --> package-47
    package-75 --> package-17
    package-164 --> package-150
    package-150 --> package-90
    package-90 --> package-12
    package-150 --> package-100
    package-100 --> package-22
    package-100 --> package-41
    package-41 --> package-29
    package-29 --> package-18
    package-29 --> package-14
    package-41 --> package-25
    package-25 --> package-12
    package-25 --> package-5
    package-25 --> package-23
    package-25 --> package-13
    package-25 --> package-19
    package-41 --> package-13
    package-41 --> package-39
    package-39 --> package-16
    package-39 --> package-28
    package-39 --> package-15
    package-39 --> package-5
    package-39 --> package-21
    package-41 --> package-37
    package-37 --> package-11
    package-37 --> package-32
    package-37 --> package-18
    package-37 --> package-16
    package-37 --> package-21
    package-100 --> package-5
    package-164 --> package-146
    package-146 --> package-52
    package-52 --> package-10
    package-10 --> package-3
    package-3 --> package-1
    package-3 --> package-2
    package-52 --> package-48
    package-48 --> package-25
    package-48 --> package-4
    package-52 --> package-4
    package-52 --> package-2
    package-266 --> package-196
    package-196 --> package-141
    package-141 --> package-137
    package-196 --> package-99
    package-99 --> package-77
    package-77 --> package-56
    package-56 --> package-34
    package-34 --> package-2
    package-34 --> package-27
    package-27 --> package-5
    package-27 --> package-9
    package-34 --> package-1
    package-34 --> package-10
    package-34 --> package-14
    package-14 --> package-10
    package-14 --> package-13
    package-56 --> package-54
    package-54 --> package-22
    package-56 --> package-5
    package-196 --> package-171
    package-171 --> package-6
    package-6 --> package-1
    package-6 --> package-4
    package-6 --> package-5
    package-6 --> package-2
    package-6 --> package-3
    package-171 --> package-141
    package-171 --> package-38
    package-38 --> package-37
    package-38 --> package-3
    package-171 --> package-106
    package-106 --> package-18
    package-18 --> package-14
    package-106 --> package-46
    package-46 --> package-30
    package-30 --> package-17
    package-106 --> package-48
    package-196 --> package-146
    package-724 --> package-535
    package-535 --> package-273
    package-535 --> package-84
    package-84 --> package-30
    package-84 --> package-55
    package-84 --> package-66
    package-66 --> package-36
    package-66 --> package-27
    package-66 --> package-1
    package-66 --> package-33
    package-33 --> package-24
    package-24 --> package-6
    package-24 --> package-20
    package-84 --> package-31
    package-31 --> package-25
    package-31 --> package-7
    package-84 --> package-75
    package-535 --> package-80
    package-80 --> package-45
    package-80 --> package-42
    package-42 --> package-19
    package-724 --> package-70
    package-724 --> package-83
    package-83 --> package-52
    package-724 --> package-186
    package-186 --> package-107
    package-107 --> package-97
    package-97 --> package-11
    package-11 --> package-3
    package-97 --> package-19
    package-97 --> package-34
    package-186 --> package-101
    package-101 --> package-92
    package-92 --> package-45
    package-92 --> package-59
    package-59 --> package-12
    package-59 --> package-27
    package-59 --> package-55
    package-59 --> package-22
    package-59 --> package-24
    package-92 --> package-78
    package-101 --> package-88
    package-88 --> package-60
    package-60 --> package-52
    package-88 --> package-36
    package-101 --> package-30
    package-101 --> package-16
    package-101 --> package-85
    package-85 --> package-2
    package-85 --> package-59
    package-186 --> package-141
    package-186 --> package-171
    package-186 --> package-64
    package-64 --> package-62
    package-62 --> package-42
    package-62 --> package-9
    package-62 --> package-39
    package-62 --> package-20
    package-62 --> package-58
    package-817 --> package-534
    package-534 --> package-357
    package-357 --> package-121
    package-121 --> package-28
    package-28 --> package-11
    package-28 --> package-27
    package-534 --> package-312
    package-312 --> package-133
    package-534 --> package-530
    package-530 --> package-269
    package-269 --> package-251
    package-251 --> package-44
    package-44 --> package-24
    package-44 --> package-22
    package-44 --> package-41
    package-44 --> package-11
    package-251 --> package-69
    package-69 --> package-48
    package-69 --> package-7
    package-69 --> package-43
    package-43 --> package-2
    package-69 --> package-14
    package-530 --> package-364
    package-530 --> package-346
    package-346 --> package-306
    package-306 --> package-76
    package-76 --> package-75
    package-76 --> package-69
    package-76 --> package-52
    package-346 --> package-242
    package-242 --> package-33
    package-242 --> package-223
    package-223 --> package-162
    package-242 --> package-238
    package-242 --> package-93
    package-534 --> package-424
    package-817 --> package-654
    package-654 --> package-486
    package-486 --> package-35
    package-35 --> package-10
    package-35 --> package-9
    package-486 --> package-363
    package-363 --> package-25
    package-363 --> package-233
    package-233 --> package-180
    package-180 --> package-5
    package-180 --> package-116
    package-116 --> package-81
    package-81 --> package-66
    package-81 --> package-4
    package-116 --> package-6
    package-116 --> package-79
    package-79 --> package-8
    package-116 --> package-12
    package-180 --> package-129
    package-129 --> package-55
    package-129 --> package-64
    package-180 --> package-141
    package-233 --> package-56
    package-233 --> package-125
    package-233 --> package-34
    package-363 --> package-316
    package-316 --> package-275
    package-275 --> package-188
    package-275 --> package-238
    package-316 --> package-65
    package-65 --> package-5
    package-316 --> package-213
    package-213 --> package-112
    package-112 --> package-71
    package-71 --> package-1
    package-71 --> package-63
    package-112 --> package-67
    package-67 --> package-2
    package-67 --> package-53
    package-67 --> package-65
    package-67 --> package-54
    package-112 --> package-38
    package-213 --> package-99
    package-316 --> package-139
    package-139 --> package-15
    package-15 --> package-14
    package-15 --> package-12
    package-139 --> package-133
    package-139 --> package-77
    package-363 --> package-100
    package-654 --> package-130
    package-130 --> package-70
    package-130 --> package-4
    package-817 --> package-295
    package-1000 --> package-557
    package-557 --> package-6
    package-557 --> package-273
    package-1000 --> package-761
    package-761 --> package-710
    package-710 --> package-20
    package-710 --> package-493
    package-710 --> package-604
    package-604 --> package-207
    package-207 --> package-73
    package-73 --> package-14
    package-73 --> package-46
    package-73 --> package-8
    package-207 --> package-182
    package-182 --> package-111
    package-111 --> package-60
    package-111 --> package-83
    package-604 --> package-92
    package-604 --> package-5
    package-604 --> package-196
    package-604 --> package-297
    package-297 --> package-23
    package-23 --> package-7
    package-23 --> package-11
    package-297 --> package-225
    package-225 --> package-102
    package-102 --> package-86
    package-102 --> package-91
    package-225 --> package-46
    package-225 --> package-124
    package-124 --> package-50
    package-50 --> package-32
    package-32 --> package-18
    package-50 --> package-26
    package-26 --> package-24
    package-26 --> package-3
    package-26 --> package-5
    package-50 --> package-24
    package-50 --> package-8
    package-50 --> package-31
    package-124 --> package-65
    package-225 --> package-87
    package-87 --> package-81
    package-87 --> package-60
    package-87 --> package-37
    package-297 --> package-31
    package-297 --> package-30
    package-297 --> package-139
    package-710 --> package-239
    package-239 --> package-29
    package-239 --> package-148
    package-148 --> package-123
    package-123 --> package-95
    package-95 --> package-78
    package-95 --> package-46
    package-95 --> package-11
    package-95 --> package-5
    package-123 --> package-59
    package-123 --> package-20
    package-148 --> package-92
    package-239 --> package-179
    package-761 --> package-178
    package-178 --> package-71
    package-1000 --> package-722
    package-722 --> package-227
    package-227 --> package-137
    package-227 --> package-212
    package-212 --> package-34
    package-227 --> package-80
    package-722 --> package-223
    package-722 --> package-121
