graph TD
    package-1000 --> package-936
    package-936 --> package-635
    package-635 --> package-245
    package-245 --> package-81
    package-81 --> package-53
    package-81 --> package-41
    package-41 --> package-3
    package-3 --> package-1
    package-3 --> package-2
    package-2 --> package-1
    package-41 --> package-32
    package-81 --> package-65
    package-65 --> package-13
    package-13 --> package-4
    package-4 --> package-1
    package-4 --> package-3
    package-13 --> package-11
    package-11 --> package-6
    package-11 --> package-8
    package-8 --> package-3
    package-65 --> package-17
    package-17 --> package-11
    package-17 --> package-13
    package-81 --> package-20
    package-81 --> package-18
    package-18 --> package-1
    package-18 --> package-17
    package-245 --> package-201
    package-201 --> package-177
    package-177 --> package-141
    package-141 --> package-112
    package-112 --> package-18
    package-141 --> package-35
    package-35 --> package-20
    package-35 --> package-21
    package-21 --> package-16
    package-16 --> package-12
    package-12 --> package-1
    package-16 --> package-10
    package-10 --> package-9
    package-16 --> package-14
    package-14 --> package-7
    package-14 --> package-4
    package-21 --> package-19
    package-19 --> package-10
    package-19 --> package-4
    package-19 --> package-6
    package-21 --> package-7
    package-7 --> package-1
    package-7 --> package-5
    package-5 --> package-1
    package-5 --> package-3
    package-7 --> package-6
    package-7 --> package-4
    package-21 --> package-5
    package-141 --> package-91
    package-91 --> package-58
    package-91 --> package-39
    package-39 --> package-9
    package-9 --> package-1
    package-9 --> package-3
    package-91 --> package-19
    package-141 --> package-104
    package-141 --> package-100
    package-100 --> package-5
    package-100 --> package-18
    package-201 --> package-109
    package-201 --> package-15
    package-201 --> package-172
    package-172 --> package-65
    package-172 --> package-86
    package-86 --> package-78
    package-86 --> package-2
    package-86 --> package-3
    package-86 --> package-50
    package-50 --> package-33
    package-33 --> package-14
    package-33 --> package-23
    package-23 --> package-9
    package-23 --> package-19
    package-33 --> package-10
    package-50 --> package-8
    package-50 --> package-47
    package-47 --> package-3
    package-47 --> package-26
    package-26 --> package-16
    package-26 --> package-9
    package-47 --> package-23
    package-47 --> package-35
    package-47 --> package-10
    package-50 --> package-17
    package-86 --> package-42
    package-172 --> package-101
    package-101 --> package-93
    package-93 --> package-23
    package-101 --> package-25
    package-25 --> package-10
    package-25 --> package-23
    package-172 --> package-21
    package-245 --> package-173
    package-173 --> package-26
    package-173 --> package-148
    package-148 --> package-15
    package-148 --> package-18
    package-148 --> package-26
    package-148 --> package-81
    package-173 --> package-31
    package-31 --> package-24
    package-31 --> package-3
    package-31 --> package-9
    package-31 --> package-8
    package-173 --> package-53
    package-245 --> package-102
    package-102 --> package-65
    package-102 --> package-49
    package-49 --> package-42
    package-49 --> package-9
    package-635 --> package-315
    package-315 --> package-133
    package-315 --> package-13
    package-635 --> package-323
    package-323 --> package-108
    package-108 --> package-99
    package-99 --> package-3
    package-108 --> package-40
    package-40 --> package-18
    package-40 --> package-23
    package-108 --> package-65
    package-108 --> package-81
    package-323 --> package-240
    package-240 --> package-68
    package-240 --> package-88
    package-88 --> package-71
    package-71 --> package-51
    package-51 --> package-40
    package-51 --> package-45
    package-45 --> package-42
    package-51 --> package-26
    package-51 --> package-14
    package-71 --> package-15
    package-71 --> package-40
    package-240 --> package-23
    package-240 --> package-105
    package-240 --> package-29
    package-29 --> package-13
    package-29 --> package-23
    package-323 --> package-163
    package-323 --> package-184
    package-184 --> package-79
    package-79 --> package-31
    package-79 --> package-27
    package-27 --> package-2
    package-27 --> package-26
    package-27 --> package-15
    package-184 --> package-170
    package-170 --> package-164
    package-164 --> package-22
    package-22 --> package-14
    package-164 --> package-7
    package-164 --> package-98
    package-98 --> package-51
    package-98 --> package-31
    package-184 --> package-40
    package-323 --> package-204
    package-936 --> package-797
    package-797 --> package-435
    package-435 --> package-432
    package-435 --> package-207
    package-207 --> package-143
    package-143 --> package-16
    package-143 --> package-38
    package-38 --> package-24
    package-38 --> package-9
    package-38 --> package-3
    package-38 --> package-15
    package-143 --> package-91
    package-143 --> package-52
    package-52 --> package-41
    package-52 --> package-39
    package-435 --> package-199
    package-199 --> package-180
    package-180 --> package-168
    package-168 --> package-48
    package-48 --> package-14
    package-48 --> package-5
    package-48 --> package-43
    package-43 --> package-23
    package-43 --> package-19
    package-43 --> package-30
    package-30 --> package-1
    package-30 --> package-20
    package-30 --> package-11
    package-168 --> package-118
    package-118 --> package-30
    package-118 --> package-35
    package-118 --> package-21
    package-118 --> package-81
    package-180 --> package-130
    package-130 --> package-4
    package-130 --> package-63
    package-63 --> package-23
    package-63 --> package-36
    package-180 --> package-82
    package-82 --> package-68
    package-82 --> package-74
    package-82 --> package-71
    package-180 --> package-8
    package-199 --> package-6
    package-199 --> package-122
    package-122 --> package-55
    package-55 --> package-47
    package-55 --> package-2
    package-55 --> package-30
    package-55 --> package-50
    package-199 --> package-73
    package-73 --> package-40
    package-73 --> package-6
    package-73 --> package-18
    package-73 --> package-1
    package-199 --> package-137
    package-137 --> package-76
    package-76 --> package-39
    package-76 --> package-12
    package-137 --> package-75
    package-75 --> package-52
    package-435 --> package-91
    package-797 --> package-140
    package-140 --> package-55
    package-140 --> package-94
    package-94 --> package-52
    package-94 --> package-56
    package-94 --> package-35
    package-94 --> package-42
    package-140 --> package-33
    package-140 --> package-46
    package-46 --> package-17
    package-46 --> package-27
    package-140 --> package-2
    package-797 --> package-270
    package-270 --> package-150
    package-150 --> package-67
    package-67 --> package-53
    package-67 --> package-29
    package-67 --> package-22
    package-67 --> package-23
    package-150 --> package-51
    package-150 --> package-148
    package-270 --> package-139
    package-797 --> package-336
    package-336 --> package-25
    package-336 --> package-80
    package-80 --> package-16
    package-80 --> package-55
    package-80 --> package-79
    package-80 --> package-42
    package-336 --> package-144
    package-144 --> package-120
    package-120 --> package-10
    package-120 --> package-89
    package-89 --> package-88
    package-89 --> package-35
    package-120 --> package-61
    package-61 --> package-60
    package-61 --> package-12
    package-61 --> package-48
    package-61 --> package-34
    package-34 --> package-14
    package-34 --> package-27
    package-61 --> package-42
    package-120 --> package-76
    package-144 --> package-55
    package-144 --> package-59
    package-336 --> package-160
    package-160 --> package-74
    package-160 --> package-70
    package-160 --> package-149
    package-149 --> package-31
    package-149 --> package-136
    package-336 --> package-138
    package-138 --> package-91
    package-138 --> package-67
    package-1000 --> package-94
